Fix region attribute name in preprocessing.py
Error when image_uri is not specified. Boto_region_name doesn't exist.
 File "/opt/conda/lib/python3.7/site-packages/sagemaker/sklearn/processing.py", line 88, in __init__
    region = session.boto_region_name
AttributeError: 'Session' object has no attribute 'boto_region_name'